name: Build
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: ['**']
jobs:
  checks:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v15
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
    with:
      filter_builds: '.top_attr == "build"'
